# -*- coding: utf-8 -*-
"""labwork1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15nsanJP4Vv5RTbG7IEDeQo3CWuQE3i47

1
"""

pi = 3.141592653589793
print("Enter the radius of the circle:")
radius = float(input())
area = radius ** 2 * pi
print("The area of the circle is:", area, end = ' area unit')

"""2"""

print("Enter Celsius temp:")
cel = float(input())
fah = 32 + 1.8 * cel
print("C to F is:", fah)

"""3"""

n = int(input("Enter a number: "))
def is_prime(n):
    if n <= 1:
        return "Not a prime number"
    if n == 2:
        return "Prime number"
    if n % 2 == 0:
        return "Not a prime number"
    for i in range(3, int(n**0.5) + 1, 2):
        if n % i == 0:
            return "Not a prime number"
    return "Prime number"
print(is_prime(n))

"""4"""

def is_perfect_number(n):
  if n in (6, 28, 494, 8128):
    return "That a freshly perfect number"
  else:
    return "Not a perfect number, and get away from me"
n = int(input())
print(is_perfect_number(n))

"""5"""

color_list = ["r","b","g","o","v","c","i","w"]
fav_color = input("Enter your favorite color: ")
if fav_color in color_list:
  index = color_list.index(fav_color)
  print("Ur color is at index", index, "in my list")
else:
  print("Cut ra ngoai")

"""6"""

while True:
    seq_name = input("Enter sequence name (ex: range1): ")
    if seq_name == "range1":
        seq = range(7)
    elif seq_name == "range2":
        seq = range(1, 13, 3)
    elif seq_name == "range3":
        seq = range(5, 0, -1)
    elif seq_name == "range4":
        seq = range(6, -3, -2)
    else:
        print("? ngao a")
        continue
    print(" ,".join(map(str, seq)))

"""7"""

def remove_dollar_sign(s):
  return s.replace('$', '')
s = input().strip()
print(remove_dollar_sign(s))

"""8"""

def extract_even(numbers):
  even_list = []
  for num in numbers:
      if num % 2 == 0:
        even_list.append(num)
  return even_list

user_input = input("Enter numbers separated by spaces: ")
try:
  numbers = list(map(int, user_input.split()))
  extracted_evens = extract_even(numbers)
  print("Even numbers extracted:", extracted_evens)
except ValueError:
  print("Invalid input. Please enter numbers separated by spaces.")

"""9"""

def factorial(n):
  if n == 0 or n == 1:
    return 1
  if n < 0:
    return "ngao ngo"
  result = 1
  for i in range(2, n + 1):
    result *= i
  return result
n = int(input())
result = factorial(n)
print(result)

"""10"""

def get_divisors():
  divisors = []
  if n == 0:
    return []
  for i in range(1, n + 1):
    if n % i == 0:
      divisors.append(i)
  return divisors
divisors = get_divisors()
n = int(input())
print(list(divisors))

"""11"""

import math
def distance(x1,y1,x2,y2):
  distance = math.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2)
  return distance
x1 = int(input())
y1 = int(input())
x2 = int(input())
y2 = int(input())
print("The distance between 2 points is:", distance(x1,y1,x2,y2))

"""12"""

def print_pattern(m, n):
  for i in range(m):
    for j in range(n):
      if i == 0 or i == m - 1 or j == 0 or j == n - 1:
        print("*", end = " ")
      else:
        print(" ", end = " ")
    print()

m_input = int(input("Enter number of rows (m): "))
n_input = int(input("Enter number of columns (n): "))

print_pattern(m_input, n_input)
